version: '3.8'

volumes:
  finance_monitoring_data:

services:
  pg_db:
    image: 'postgres:latest'
    container_name: finance_monitoring_pg_db
    environment:
      POSTGRES_DB: 'finance_db'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    expose:
      - '5432'
    volumes:
      - ./services/finance_monitoring_data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    container_name: finance_monitoring_pgadmin
    depends_on:
      - pg_db
    environment:
      PGADMIN_DEFAULT_EMAIL: "aaa@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./services/pgadmin:/var/lib/pgadmin

  backend:
    build: .
    container_name: finance-monitoring-backend
    depends_on:
      - pg_db
    expose:
      - "8080"

  static-server:
    image: nginx:alpine
    container_name: my-static-server
    depends_on:
      - backend
    ports:
      - "8086:81"
    volumes:
      - ./src/main/resources:/usr/share/nginx/html:ro
      - ./src/main/resources/frontend.conf:/etc/nginx/conf.d/frontend.conf:ro