version: '3.8'

volumes:
  finance_monitoring_data:

networks:
  dev_backend:

services:

  pg_db:
    image: 'postgres:latest'
    container_name: finance_monitoring_pg_db
    environment:
      POSTGRES_DB: 'finance_db'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - '5438:5432'
    volumes:
      - ./services/finance_monitoring_data:/var/lib/postgresql/data
      - ./src/main/resources:/docker-entrypoint-initdb.d
    networks:
      - dev_backend

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    container_name: pgadmin
    depends_on:
      - pg_db
    environment:
      PGADMIN_DEFAULT_EMAIL: "aaa@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./services/pgadmin:/var/lib/pgadmin
    networks:
      - dev_backend

  static-server:
    image: nginx:alpine
    container_name: my-static-server
    ports:
      - "8086:81"
    volumes:
      - ./src/main/resources:/usr/share/nginx/html:ro
      - ./src/main/resources/frontend.conf:/etc/nginx/conf.d/frontend.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"