name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: start services
        run: docker-compose up -d

      - name: Wait
        run: while [ "$(curl -s localhost:8086/api/auth/login)" != '{"error":"Method not allowed"}' ]; do sleep 1; done

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Tests
        run: mvn test